// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It contains the AWS resources configuration.

const awsconfig = {
    Auth: {
        region: process.env.REACT_APP_AWS_REGION,
        userPoolId: process.env.REACT_APP_USER_POOL_ID,
        userPoolWebClientId: process.env.REACT_APP_USER_POOL_WEB_CLIENT_ID,
        mandatorySignIn: true,
    }
};

export default awsconfig;
