/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.


const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ToEZ3Lwdq",
    "aws_user_pools_web_client_id": "qbuo5l9eogm4t0ivr0n8juoif",  
};

export default awsmobile;
